-- Ensure every currently supported target-role family has a safe MCQ-only Challenge Me path.
insert into public.assessment_question_bank(
  id,skill_id,concept_id,type,difficulty,prompt,options,answer_key,rubric,tags,source,version,is_active
) values
('40000000-0000-0000-0000-000000000301','10000000-0000-0000-0000-000000000008','session-vs-token','MCQ',2,
'Which statement best distinguishes a server-side session from a self-contained signed token?',
'[{"id":"a","text":"A session typically keeps authoritative login state on the server, while a signed token can carry claims that the server verifies."},{"id":"b","text":"They are always identical."},{"id":"c","text":"A signed token cannot expire."},{"id":"d","text":"Sessions never use cookies."}]'::jsonb,
'{"correctOptionId":"a"}'::jsonb,
'{"correctFeedback":"Sessions commonly keep authoritative state server-side, while signed tokens can carry verifiable claims.","incorrectFeedback":"Focus on where authoritative authentication state and claims are stored."}'::jsonb,
'["authentication","sessions","tokens"]'::jsonb,'SEEDED','core-mcq-f1',true),
('40000000-0000-0000-0000-000000000302','10000000-0000-0000-0000-000000000008','authorization','MCQ',2,
'An authenticated user is allowed to read a document only if they own it. Which concern is being enforced?',
'[{"id":"a","text":"Authentication only"},{"id":"b","text":"Authorization"},{"id":"c","text":"Serialization"},{"id":"d","text":"Caching"}]'::jsonb,
'{"correctOptionId":"b"}'::jsonb,
'{"correctFeedback":"Authorization determines what an authenticated identity is permitted to do.","incorrectFeedback":"Authentication establishes identity; authorization controls permissions."}'::jsonb,
'["authentication","authorization","access-control"]'::jsonb,'SEEDED','core-mcq-f1',true),

('40000000-0000-0000-0000-000000000303','10000000-0000-0000-0000-000000000009','images-containers','MCQ',1,
'What is the best description of a Docker image?',
'[{"id":"a","text":"A running process only"},{"id":"b","text":"An immutable template used to create containers"},{"id":"c","text":"A physical virtual machine"},{"id":"d","text":"A DNS record"}]'::jsonb,
'{"correctOptionId":"b"}'::jsonb,
'{"correctFeedback":"A Docker image is the packaged template from which containers are created.","incorrectFeedback":"Distinguish the packaged image from a running container instance."}'::jsonb,
'["docker","images","containers"]'::jsonb,'SEEDED','core-mcq-f1',true),
('40000000-0000-0000-0000-000000000304','10000000-0000-0000-0000-000000000009','dockerfile-cache','MCQ',2,
'Why is it useful to place rarely changing Dockerfile steps before frequently changing source-code copies?',
'[{"id":"a","text":"To improve layer-cache reuse"},{"id":"b","text":"To disable networking"},{"id":"c","text":"To remove the base image"},{"id":"d","text":"To make every build start from scratch"}]'::jsonb,
'{"correctOptionId":"a"}'::jsonb,
'{"correctFeedback":"Stable earlier layers can be reused from the build cache when later source files change.","incorrectFeedback":"Docker builds cache layers; ordering affects how much work can be reused."}'::jsonb,
'["docker","dockerfile","cache"]'::jsonb,'SEEDED','core-mcq-f1',true),

('40000000-0000-0000-0000-000000000305','10000000-0000-0000-0000-000000000006','safe-methods','MCQ',1,
'Which HTTP method is conventionally considered safe because it is intended only to retrieve a representation?',
'[{"id":"a","text":"GET"},{"id":"b","text":"POST"},{"id":"c","text":"PATCH"},{"id":"d","text":"DELETE"}]'::jsonb,
'{"correctOptionId":"a"}'::jsonb,
'{"correctFeedback":"GET is conventionally a safe retrieval method.","incorrectFeedback":"Safe methods are intended not to request a state-changing action."}'::jsonb,
'["http","methods","safe-methods"]'::jsonb,'SEEDED','core-mcq-f1',true),
('40000000-0000-0000-0000-000000000306','10000000-0000-0000-0000-000000000006','content-type','MCQ',2,
'What does the HTTP Content-Type header primarily describe?',
'[{"id":"a","text":"The media type of the message content"},{"id":"b","text":"The server IP address"},{"id":"c","text":"The HTTP method"},{"id":"d","text":"The TCP port chosen by the client"}]'::jsonb,
'{"correctOptionId":"a"}'::jsonb,
'{"correctFeedback":"Content-Type identifies the media type of the message content.","incorrectFeedback":"Content-Type describes the representation carried in the HTTP message."}'::jsonb,
'["http","headers","content-type"]'::jsonb,'SEEDED','core-mcq-f1',true),

('40000000-0000-0000-0000-000000000307','10000000-0000-0000-0000-000000000004','joins','MCQ',2,
'Which SQL join returns only rows that have matching join keys in both input tables?',
'[{"id":"a","text":"INNER JOIN"},{"id":"b","text":"LEFT JOIN"},{"id":"c","text":"FULL OUTER JOIN"},{"id":"d","text":"CROSS JOIN"}]'::jsonb,
'{"correctOptionId":"a"}'::jsonb,
'{"correctFeedback":"INNER JOIN retains rows for which the join condition matches on both sides.","incorrectFeedback":"Choose the join that excludes unmatched rows from both inputs."}'::jsonb,
'["sql","joins"]'::jsonb,'SEEDED','core-mcq-f1',true),
('40000000-0000-0000-0000-000000000308','10000000-0000-0000-0000-000000000004','grouping','MCQ',2,
'Which SQL clause filters grouped aggregate results after GROUP BY?',
'[{"id":"a","text":"WHERE"},{"id":"b","text":"HAVING"},{"id":"c","text":"ORDER BY"},{"id":"d","text":"VALUES"}]'::jsonb,
'{"correctOptionId":"b"}'::jsonb,
'{"correctFeedback":"HAVING filters groups after aggregation.","incorrectFeedback":"WHERE filters rows before grouping; HAVING filters grouped results."}'::jsonb,
'["sql","group-by","having"]'::jsonb,'SEEDED','core-mcq-f1',true)
on conflict(id) do update set
  prompt=excluded.prompt,options=excluded.options,answer_key=excluded.answer_key,
  rubric=excluded.rubric,tags=excluded.tags,difficulty=excluded.difficulty,
  version=excluded.version,is_active=true;
