-- Extended adaptive assessment bank and concept-signal terminology.

alter table public.skill_assessment_concept_signals
  drop constraint if exists skill_assessment_concept_signals_polarity_check;

alter table public.skill_assessment_concept_signals
  add constraint skill_assessment_concept_signals_polarity_check
  check (polarity in ('SUPPORTS','CONTRADICTS','MIXED','POSITIVE','NEGATIVE'));

-- REST short/scenario items
insert into public.assessment_question_bank(
  id,skill_id,concept_id,type,difficulty,prompt,options,answer_key,rubric,tags,source,version,is_active
) values
('40000000-0000-0000-0000-000000000007','10000000-0000-0000-0000-000000000007','idempotency','SHORT_TEXT',3,
'In one or two sentences, explain why retrying the same PUT request is expected to be idempotent while retrying a typical POST create request may not be.',
null,
'{"expectedKeywords":["same intended effect","idempotent","PUT","POST","duplicate"],"referenceAnswer":"Repeating the same PUT should leave the resource in the same intended state, while repeating a POST create may create additional resources unless the API adds its own idempotency mechanism."}'::jsonb,
'{"criteria":[{"id":"effect","weight":0.5,"description":"Explains same intended server-side effect for repeated PUT"},{"id":"post","weight":0.5,"description":"Explains repeated POST may duplicate creation without extra idempotency controls"}],"maxScore":1}'::jsonb,
'["rest-api","http","idempotency"]'::jsonb,'SEEDED','adaptive-bank-e2',true),
('40000000-0000-0000-0000-000000000008','10000000-0000-0000-0000-000000000007','update-semantics','SCENARIO',3,
'An API stores a user with name, email, and avatarUrl. A mobile client wants to change only avatarUrl. Describe the HTTP method and update semantics you would choose, including what should happen to omitted fields.',
null,
'{"expectedKeywords":["PATCH","partial","omitted","unchanged"],"referenceAnswer":"Use PATCH for a partial update and leave omitted fields unchanged."}'::jsonb,
'{"criteria":[{"id":"method","weight":0.45,"description":"Chooses PATCH or clearly equivalent partial-update semantics"},{"id":"omitted","weight":0.35,"description":"States omitted fields remain unchanged"},{"id":"reasoning","weight":0.20,"description":"Distinguishes partial modification from full replacement"}],"maxScore":1}'::jsonb,
'["rest-api","patch","update-semantics"]'::jsonb,'SEEDED','adaptive-bank-e2',true),
('40000000-0000-0000-0000-000000000009','10000000-0000-0000-0000-000000000007','resource-design','SCENARIO',4,
'Design resource-oriented endpoints for creating a task, archiving task 42, and restoring task 42. Briefly justify the resource/action modeling.',
null,
'{"expectedKeywords":["tasks","42","archive","restore"],"referenceAnswer":"Use resource-oriented task URLs and model archive/restore as state-changing subresources or explicit domain actions while keeping nouns stable."}'::jsonb,
'{"criteria":[{"id":"resource","weight":0.35,"description":"Uses stable task resource nouns"},{"id":"operations","weight":0.35,"description":"Models archive/restore consistently without get-style verbs"},{"id":"tradeoff","weight":0.30,"description":"Explains why the chosen design is consistent and observable"}],"maxScore":1}'::jsonb,
'["rest-api","resource-design","tradeoffs"]'::jsonb,'SEEDED','adaptive-bank-e2',true),

-- HTTP bank
('40000000-0000-0000-0000-000000000101','10000000-0000-0000-0000-000000000006','methods','MCQ',1,
'Which HTTP method is defined as safe and typically used to retrieve a representation?',
'[{"id":"a","text":"GET"},{"id":"b","text":"POST"},{"id":"c","text":"PATCH"},{"id":"d","text":"DELETE"}]'::jsonb,
'{"correctOptionId":"a"}'::jsonb,
'{"correctFeedback":"GET is a safe retrieval method.","incorrectFeedback":"Review safe HTTP method semantics."}'::jsonb,
'["http","methods"]'::jsonb,'SEEDED','adaptive-bank-e2',true),
('40000000-0000-0000-0000-000000000102','10000000-0000-0000-0000-000000000006','status-codes','MCQ',2,
'Which status best represents a successful request with intentionally no response body?',
'[{"id":"a","text":"201"},{"id":"b","text":"204"},{"id":"c","text":"302"},{"id":"d","text":"409"}]'::jsonb,
'{"correctOptionId":"b"}'::jsonb,
'{"correctFeedback":"204 No Content communicates success with no representation body.","incorrectFeedback":"Review successful 2xx status semantics."}'::jsonb,
'["http","status-codes"]'::jsonb,'SEEDED','adaptive-bank-e2',true),
('40000000-0000-0000-0000-000000000103','10000000-0000-0000-0000-000000000006','caching','SHORT_TEXT',2,
'What is the purpose of an ETag in HTTP caching and conditional requests?',
null,
'{"expectedKeywords":["validator","If-None-Match","304","representation"],"referenceAnswer":"An ETag is a representation validator that lets clients make conditional requests such as If-None-Match and receive 304 when unchanged."}'::jsonb,
'{"criteria":[{"id":"validator","weight":0.6,"description":"Identifies ETag as a representation/cache validator"},{"id":"conditional","weight":0.4,"description":"Connects it to conditional requests/304 behavior"}],"maxScore":1}'::jsonb,
'["http","caching","etag"]'::jsonb,'SEEDED','adaptive-bank-e2',true),
('40000000-0000-0000-0000-000000000104','10000000-0000-0000-0000-000000000006','headers','SCENARIO',3,
'A JSON API returns HTML because content negotiation is misconfigured. Which request and response headers would you inspect first, and why?',
null,
'{"expectedKeywords":["Accept","Content-Type","application/json"],"referenceAnswer":"Inspect Accept on the request and Content-Type on the response to verify the negotiated representation is application/json."}'::jsonb,
'{"criteria":[{"id":"accept","weight":0.45,"description":"Mentions request Accept header"},{"id":"contentType","weight":0.45,"description":"Mentions response Content-Type"},{"id":"reasoning","weight":0.10,"description":"Connects headers to representation negotiation"}],"maxScore":1}'::jsonb,
'["http","headers","content-negotiation"]'::jsonb,'SEEDED','adaptive-bank-e2',true),

-- SQL bank
('40000000-0000-0000-0000-000000000201','10000000-0000-0000-0000-000000000004','filtering','MCQ',1,
'Which SQL clause filters rows before grouping?',
'[{"id":"a","text":"WHERE"},{"id":"b","text":"HAVING"},{"id":"c","text":"ORDER BY"},{"id":"d","text":"LIMIT"}]'::jsonb,
'{"correctOptionId":"a"}'::jsonb,
'{"correctFeedback":"WHERE filters rows before aggregation.","incorrectFeedback":"HAVING filters groups after aggregation; WHERE filters rows first."}'::jsonb,
'["sql","where"]'::jsonb,'SEEDED','adaptive-bank-e2',true),
('40000000-0000-0000-0000-000000000202','10000000-0000-0000-0000-000000000004','joins','MCQ',2,
'You need every customer even when they have no orders. Which join from customers to orders is appropriate?',
'[{"id":"a","text":"INNER JOIN"},{"id":"b","text":"LEFT JOIN"},{"id":"c","text":"CROSS JOIN"},{"id":"d","text":"SELF JOIN"}]'::jsonb,
'{"correctOptionId":"b"}'::jsonb,
'{"correctFeedback":"LEFT JOIN preserves all rows from customers.","incorrectFeedback":"Use the join that preserves all rows from the left table."}'::jsonb,
'["sql","joins"]'::jsonb,'SEEDED','adaptive-bank-e2',true),
('40000000-0000-0000-0000-000000000203','10000000-0000-0000-0000-000000000004','aggregation','SHORT_TEXT',2,
'Explain the difference between WHERE and HAVING when writing an aggregate query.',
null,
'{"expectedKeywords":["WHERE","rows","HAVING","groups","aggregate"],"referenceAnswer":"WHERE filters input rows before grouping; HAVING filters grouped/aggregated results after GROUP BY."}'::jsonb,
'{"criteria":[{"id":"where","weight":0.5,"description":"WHERE filters input rows before grouping"},{"id":"having","weight":0.5,"description":"HAVING filters aggregate groups/results"}],"maxScore":1}'::jsonb,
'["sql","aggregation"]'::jsonb,'SEEDED','adaptive-bank-e2',true),
('40000000-0000-0000-0000-000000000204','10000000-0000-0000-0000-000000000004','indexing','SCENARIO',3,
'A query frequently filters orders by customer_id and created_at. What index would you consider first, and what caveat would you verify before adding it?',
null,
'{"expectedKeywords":["composite","customer_id","created_at","selectivity","write"],"referenceAnswer":"Consider a composite index beginning with customer_id and then created_at if it matches the query pattern; verify selectivity, ordering needs, and write/storage cost."}'::jsonb,
'{"criteria":[{"id":"index","weight":0.55,"description":"Proposes a reasonable composite index aligned with predicates"},{"id":"tradeoff","weight":0.45,"description":"Mentions selectivity/query plan/write or storage cost"}],"maxScore":1}'::jsonb,
'["sql","indexing","tradeoffs"]'::jsonb,'SEEDED','adaptive-bank-e2',true),

-- Docker bank
('40000000-0000-0000-0000-000000000301','10000000-0000-0000-0000-000000000009','image-container','MCQ',1,
'Which statement best distinguishes a Docker image from a container?',
'[{"id":"a","text":"An image is a running process; a container is source code"},{"id":"b","text":"An image is an immutable template; a container is a runtime instance"},{"id":"c","text":"They are identical"},{"id":"d","text":"A container exists only in Docker Hub"}]'::jsonb,
'{"correctOptionId":"b"}'::jsonb,
'{"correctFeedback":"A container is a runtime instance created from an image.","incorrectFeedback":"Review image versus container lifecycle."}'::jsonb,
'["docker","images","containers"]'::jsonb,'SEEDED','adaptive-bank-e2',true),
('40000000-0000-0000-0000-000000000302','10000000-0000-0000-0000-000000000009','dockerfile','MCQ',2,
'Which Dockerfile instruction normally defines the base image?',
'[{"id":"a","text":"RUN"},{"id":"b","text":"COPY"},{"id":"c","text":"FROM"},{"id":"d","text":"CMD"}]'::jsonb,
'{"correctOptionId":"c"}'::jsonb,
'{"correctFeedback":"FROM establishes the base image/stage.","incorrectFeedback":"Review Dockerfile build instructions."}'::jsonb,
'["docker","dockerfile"]'::jsonb,'SEEDED','adaptive-bank-e2',true),
('40000000-0000-0000-0000-000000000303','10000000-0000-0000-0000-000000000009','layers','SHORT_TEXT',2,
'Why can Dockerfile instruction ordering affect build-cache efficiency?',
null,
'{"expectedKeywords":["layers","cache","invalidate","COPY"],"referenceAnswer":"Each instruction creates/cache-checks a layer; changing an early layer invalidates later layers, so stable steps should usually appear before frequently changing source copies."}'::jsonb,
'{"criteria":[{"id":"layers","weight":0.5,"description":"Connects instructions to cached image layers"},{"id":"invalidation","weight":0.5,"description":"Explains earlier changes invalidate later cached layers"}],"maxScore":1}'::jsonb,
'["docker","layers","cache"]'::jsonb,'SEEDED','adaptive-bank-e2',true),
('40000000-0000-0000-0000-000000000304','10000000-0000-0000-0000-000000000009','networking','SCENARIO',3,
'Two containers in the same Compose application need to communicate. Should the API container call localhost:5432 to reach the database container? Explain the correct approach.',
null,
'{"expectedKeywords":["service name","network","localhost","database"],"referenceAnswer":"No. localhost points to the API container itself; use the database service/container DNS name on the shared Compose network."}'::jsonb,
'{"criteria":[{"id":"localhost","weight":0.45,"description":"Explains localhost is the current container"},{"id":"serviceDns","weight":0.55,"description":"Uses service/container DNS name on the shared network"}],"maxScore":1}'::jsonb,
'["docker","networking","compose"]'::jsonb,'SEEDED','adaptive-bank-e2',true),

-- Authentication bank
('40000000-0000-0000-0000-000000000401','10000000-0000-0000-0000-000000000008','authn-authz','MCQ',1,
'Authentication answers which question?',
'[{"id":"a","text":"What may this user do?"},{"id":"b","text":"Who is this user?"},{"id":"c","text":"How fast is the API?"},{"id":"d","text":"Which database table is used?"}]'::jsonb,
'{"correctOptionId":"b"}'::jsonb,
'{"correctFeedback":"Authentication establishes identity.","incorrectFeedback":"Authorization is about permissions; authentication is about identity."}'::jsonb,
'["authentication","authorization"]'::jsonb,'SEEDED','adaptive-bank-e2',true),
('40000000-0000-0000-0000-000000000402','10000000-0000-0000-0000-000000000008','passwords','MCQ',2,
'How should application passwords normally be stored?',
'[{"id":"a","text":"Plain text"},{"id":"b","text":"Reversible encryption with a shared key"},{"id":"c","text":"A slow salted password hash"},{"id":"d","text":"Base64 encoding"}]'::jsonb,
'{"correctOptionId":"c"}'::jsonb,
'{"correctFeedback":"Use a purpose-built slow salted password hashing function.","incorrectFeedback":"Passwords should not be recoverable from storage."}'::jsonb,
'["authentication","passwords"]'::jsonb,'SEEDED','adaptive-bank-e2',true),
('40000000-0000-0000-0000-000000000403','10000000-0000-0000-0000-000000000008','jwt','SHORT_TEXT',2,
'Why should a server still verify a JWT signature rather than merely decode its payload?',
null,
'{"expectedKeywords":["signature","tamper","trust","verify"],"referenceAnswer":"Decoding only reads claims; signature verification proves the token was issued by a trusted signer and was not modified."}'::jsonb,
'{"criteria":[{"id":"tamper","weight":0.5,"description":"Explains decoding does not prevent claim tampering"},{"id":"trust","weight":0.5,"description":"Connects signature verification to trusted issuer/integrity"}],"maxScore":1}'::jsonb,
'["authentication","jwt"]'::jsonb,'SEEDED','adaptive-bank-e2',true),
('40000000-0000-0000-0000-000000000404','10000000-0000-0000-0000-000000000008','authorization','SCENARIO',3,
'An authenticated user changes the userId path parameter to another account and the API returns that account. What authorization check is missing?',
null,
'{"expectedKeywords":["object","ownership","authorization","resource"],"referenceAnswer":"The API must authorize access to the requested object/resource, verifying ownership or permission rather than trusting the path parameter."}'::jsonb,
'{"criteria":[{"id":"objectAuth","weight":0.7,"description":"Identifies object/resource-level authorization or ownership check"},{"id":"trustBoundary","weight":0.3,"description":"Explains client-supplied identifiers are not authorization"}],"maxScore":1}'::jsonb,
'["authentication","authorization","idor"]'::jsonb,'SEEDED','adaptive-bank-e2',true)
on conflict(id) do update set
  prompt=excluded.prompt,options=excluded.options,answer_key=excluded.answer_key,rubric=excluded.rubric,tags=excluded.tags,
  difficulty=excluded.difficulty,version=excluded.version,is_active=true;
