-- Broaden P1 Challenge Me coverage across seeded role families.
-- Each newly covered core skill has four validated items so it can be selected by the adaptive assessment service.

insert into public.assessment_question_bank(
  id,skill_id,concept_id,type,difficulty,prompt,options,answer_key,rubric,tags,source,version,is_active
) values

-- Python
('72000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000001','collections','MCQ',1,
'Which Python built-in collection stores unique values and supports fast membership checks?',
'[{"id":"a","text":"list"},{"id":"b","text":"set"},{"id":"c","text":"tuple"},{"id":"d","text":"str"}]'::jsonb,
'{"correctOptionId":"b"}'::jsonb,
'{"correctFeedback":"A set stores unique values and is designed for efficient membership checks.","incorrectFeedback":"Choose the collection whose elements are unique and hash-based."}'::jsonb,
'["python","collections","set"]'::jsonb,'SEEDED','role-bank-h1',true),
('72000000-0000-0000-0000-000000000002','10000000-0000-0000-0000-000000000001','exceptions','MCQ',2,
'What is the primary purpose of a try/except block in Python?',
'[{"id":"a","text":"To define a class"},{"id":"b","text":"To handle exceptions without unconditionally terminating the program"},{"id":"c","text":"To import packages"},{"id":"d","text":"To make every function asynchronous"}]'::jsonb,
'{"correctOptionId":"b"}'::jsonb,
'{"correctFeedback":"try/except lets code handle specified exceptions deliberately.","incorrectFeedback":"Think about controlled handling of runtime errors."}'::jsonb,
'["python","exceptions"]'::jsonb,'SEEDED','role-bank-h1',true),
('72000000-0000-0000-0000-000000000003','10000000-0000-0000-0000-000000000001','comprehensions','MCQ',2,
'What does the expression [x * 2 for x in values if x > 0] produce?',
'[{"id":"a","text":"A new list containing doubled positive values"},{"id":"b","text":"A set of all values"},{"id":"c","text":"A generator that can be used only once"},{"id":"d","text":"A dictionary keyed by x"}]'::jsonb,
'{"correctOptionId":"a"}'::jsonb,
'{"correctFeedback":"The list comprehension filters positive values and transforms each one.","incorrectFeedback":"Read the expression as filter first, then transform into a list."}'::jsonb,
'["python","comprehension"]'::jsonb,'SEEDED','role-bank-h1',true),
('72000000-0000-0000-0000-000000000004','10000000-0000-0000-0000-000000000001','mutability','SHORT_TEXT',3,
'Why can using a mutable object such as a list as a default function argument cause surprising behavior in Python?',
null,
'{"referenceAnswer":"Default argument objects are created once when the function is defined, so mutations can persist across later calls that reuse the same default object.","expectedKeywords":["default","once","mutation","calls"]}'::jsonb,
'{"criteria":[{"id":"lifetime","weight":0.5,"description":"Explains the default object is created once rather than per call"},{"id":"mutation","weight":0.5,"description":"Explains mutations can persist across calls"}],"maxScore":1}'::jsonb,
'["python","functions","mutability"]'::jsonb,'SEEDED','role-bank-h1',true),

-- React
('72000000-0000-0000-0000-000000000011','10000000-0000-0000-0000-000000000018','state','MCQ',1,
'What is React component state primarily used for?',
'[{"id":"a","text":"Values that can change over time and affect rendering"},{"id":"b","text":"Only global CSS variables"},{"id":"c","text":"Database schema migrations"},{"id":"d","text":"Static HTML comments"}]'::jsonb,
'{"correctOptionId":"a"}'::jsonb,
'{"correctFeedback":"State represents changing component data that can drive a re-render.","incorrectFeedback":"State is used for data whose changes should be reflected in the UI."}'::jsonb,
'["react","state"]'::jsonb,'SEEDED','role-bank-h1',true),
('72000000-0000-0000-0000-000000000012','10000000-0000-0000-0000-000000000018','keys','MCQ',2,
'Why should items rendered from a React list have stable keys?',
'[{"id":"a","text":"To help React identify which items changed, moved, or were removed"},{"id":"b","text":"To encrypt component props"},{"id":"c","text":"To make HTTP requests faster"},{"id":"d","text":"To replace state"}]'::jsonb,
'{"correctOptionId":"a"}'::jsonb,
'{"correctFeedback":"Stable keys help reconciliation preserve item identity across renders.","incorrectFeedback":"Keys are about identity during list reconciliation."}'::jsonb,
'["react","keys","reconciliation"]'::jsonb,'SEEDED','role-bank-h1',true),
('72000000-0000-0000-0000-000000000013','10000000-0000-0000-0000-000000000018','effects','MCQ',2,
'Which useEffect dependency array runs an effect after the initial mount and not again because of dependency changes?',
'[{"id":"a","text":"No dependency array"},{"id":"b","text":"An empty array []"},{"id":"c","text":"[true, false]"},{"id":"d","text":"null"}]'::jsonb,
'{"correctOptionId":"b"}'::jsonb,
'{"correctFeedback":"An empty dependency array means there are no reactive dependencies that trigger later reruns.","incorrectFeedback":"Compare an omitted dependency array with an empty one."}'::jsonb,
'["react","effects","hooks"]'::jsonb,'SEEDED','role-bank-h1',true),
('72000000-0000-0000-0000-000000000014','10000000-0000-0000-0000-000000000018','derived-state','SCENARIO',3,
'A component stores filteredItems in state even though it can be calculated from items and filter props. What simpler design would you use and why?',
null,
'{"referenceAnswer":"Derive filteredItems during rendering, or memoize the calculation if it is expensive, instead of duplicating derivable data in state because duplicated state can become stale or inconsistent.","expectedKeywords":["derive","props","state","stale"]}'::jsonb,
'{"criteria":[{"id":"derive","weight":0.55,"description":"Recommends deriving the value from existing inputs instead of duplicating it in state"},{"id":"consistency","weight":0.45,"description":"Explains duplicated state can become stale or inconsistent"}],"maxScore":1}'::jsonb,
'["react","derived-state"]'::jsonb,'SEEDED','role-bank-h1',true),

-- Statistics
('72000000-0000-0000-0000-000000000021','10000000-0000-0000-0000-000000000022','mean-median','MCQ',1,
'Which measure of center is usually more robust to a few extreme outliers?',
'[{"id":"a","text":"Median"},{"id":"b","text":"Mean"},{"id":"c","text":"Range"},{"id":"d","text":"Variance"}]'::jsonb,
'{"correctOptionId":"a"}'::jsonb,
'{"correctFeedback":"The median is less affected by a small number of extreme values.","incorrectFeedback":"Think about which measure depends on the exact magnitude of every observation."}'::jsonb,
'["statistics","median","outliers"]'::jsonb,'SEEDED','role-bank-h1',true),
('72000000-0000-0000-0000-000000000022','10000000-0000-0000-0000-000000000022','correlation','MCQ',2,
'What does a correlation close to zero establish?',
'[{"id":"a","text":"There is little linear association, but other relationships may still exist"},{"id":"b","text":"The variables are guaranteed independent"},{"id":"c","text":"One variable causes the other"},{"id":"d","text":"Both variables are constant"}]'::jsonb,
'{"correctOptionId":"a"}'::jsonb,
'{"correctFeedback":"Near-zero correlation indicates little linear association, not necessarily independence.","incorrectFeedback":"Correlation summarizes linear association and does not prove causality or independence."}'::jsonb,
'["statistics","correlation"]'::jsonb,'SEEDED','role-bank-h1',true),
('72000000-0000-0000-0000-000000000023','10000000-0000-0000-0000-000000000022','sampling','MCQ',2,
'Why is random sampling useful when estimating a population property?',
'[{"id":"a","text":"It helps reduce systematic selection bias"},{"id":"b","text":"It guarantees every estimate is exact"},{"id":"c","text":"It removes all measurement error"},{"id":"d","text":"It makes sample size irrelevant"}]'::jsonb,
'{"correctOptionId":"a"}'::jsonb,
'{"correctFeedback":"Random sampling helps avoid systematic selection patterns that bias estimates.","incorrectFeedback":"Random sampling improves representativeness; it does not guarantee exact estimates."}'::jsonb,
'["statistics","sampling","bias"]'::jsonb,'SEEDED','role-bank-h1',true),
('72000000-0000-0000-0000-000000000024','10000000-0000-0000-0000-000000000022','confidence-interval','SHORT_TEXT',3,
'In plain language, what does a 95% confidence interval procedure mean?',
null,
'{"referenceAnswer":"If the same sampling procedure were repeated many times, about 95% of the intervals constructed by that procedure would contain the true parameter; it is not a 95% probability statement about a fixed parameter after the interval is observed.","expectedKeywords":["repeated","intervals","95%","parameter"]}'::jsonb,
'{"criteria":[{"id":"repetition","weight":0.55,"description":"Explains repeated-sampling coverage"},{"id":"parameter","weight":0.45,"description":"Distinguishes procedure coverage from a posterior probability about a fixed parameter"}],"maxScore":1}'::jsonb,
'["statistics","confidence-interval"]'::jsonb,'SEEDED','role-bank-h1',true),

-- Machine Learning
('72000000-0000-0000-0000-000000000031','10000000-0000-0000-0000-000000000027','supervised-learning','MCQ',1,
'What distinguishes supervised learning from unsupervised learning?',
'[{"id":"a","text":"Supervised learning trains from examples with target labels or values"},{"id":"b","text":"Supervised learning never uses data"},{"id":"c","text":"Unsupervised learning always predicts a labeled target"},{"id":"d","text":"They are identical"}]'::jsonb,
'{"correctOptionId":"a"}'::jsonb,
'{"correctFeedback":"Supervised learning uses labeled targets to learn a predictive relationship.","incorrectFeedback":"Focus on whether the training examples include a target to predict."}'::jsonb,
'["machine-learning","supervised-learning"]'::jsonb,'SEEDED','role-bank-h1',true),
('72000000-0000-0000-0000-000000000032','10000000-0000-0000-0000-000000000027','data-leakage','MCQ',2,
'Which situation is an example of data leakage?',
'[{"id":"a","text":"A feature contains information that would not be available at prediction time"},{"id":"b","text":"Training on fewer rows than exist in the source table"},{"id":"c","text":"Using a validation set"},{"id":"d","text":"Shuffling training rows"}]'::jsonb,
'{"correctOptionId":"a"}'::jsonb,
'{"correctFeedback":"Leakage occurs when training features expose information unavailable at real prediction time.","incorrectFeedback":"Look for information that improperly crosses the train/prediction-time boundary."}'::jsonb,
'["machine-learning","data-leakage"]'::jsonb,'SEEDED','role-bank-h1',true),
('72000000-0000-0000-0000-000000000033','10000000-0000-0000-0000-000000000027','bias-variance','MCQ',3,
'A model performs poorly on both training and validation data. Which issue is most consistent with that pattern?',
'[{"id":"a","text":"Underfitting / high bias"},{"id":"b","text":"Severe overfitting only"},{"id":"c","text":"Perfect generalization"},{"id":"d","text":"Data leakage is proven"}]'::jsonb,
'{"correctOptionId":"a"}'::jsonb,
'{"correctFeedback":"Poor performance even on training data is a classic sign of underfitting or high bias.","incorrectFeedback":"Overfitting usually has much stronger training performance than validation performance."}'::jsonb,
'["machine-learning","bias-variance","underfitting"]'::jsonb,'SEEDED','role-bank-h1',true),
('72000000-0000-0000-0000-000000000034','10000000-0000-0000-0000-000000000027','pipeline-leakage','SCENARIO',3,
'You standardize the entire dataset before splitting into train and test sets. What is wrong with this workflow, and how should you fix it?',
null,
'{"referenceAnswer":"Fitting the scaler on all data leaks information from the test set. Split first, fit preprocessing only on the training data, and apply the fitted transformation to validation/test data, ideally inside a pipeline.","expectedKeywords":["leakage","split","training","scaler"]}'::jsonb,
'{"criteria":[{"id":"leakage","weight":0.5,"description":"Identifies test-set information leakage"},{"id":"fix","weight":0.5,"description":"Fits preprocessing on training data only and applies it to held-out data"}],"maxScore":1}'::jsonb,
'["machine-learning","pipeline","data-leakage"]'::jsonb,'SEEDED','role-bank-h1',true),

-- Product Strategy
('72000000-0000-0000-0000-000000000041','10000000-0000-0000-0000-000000000031','problem-outcome','MCQ',1,
'Which statement is the clearest product outcome rather than an output?',
'[{"id":"a","text":"Increase the percentage of new users who complete activation"},{"id":"b","text":"Ship three onboarding screens"},{"id":"c","text":"Create ten tickets"},{"id":"d","text":"Add two buttons"}]'::jsonb,
'{"correctOptionId":"a"}'::jsonb,
'{"correctFeedback":"An outcome describes a user or business behavior/result rather than the artifact shipped.","incorrectFeedback":"Distinguish the change you want to create from the feature or task you produce."}'::jsonb,
'["product-strategy","outcomes"]'::jsonb,'SEEDED','role-bank-h1',true),
('72000000-0000-0000-0000-000000000042','10000000-0000-0000-0000-000000000031','segmentation','MCQ',2,
'Why is a clearly defined target user segment useful in product strategy?',
'[{"id":"a","text":"It makes needs, tradeoffs, and positioning more specific"},{"id":"b","text":"It guarantees every user wants the same thing"},{"id":"c","text":"It removes the need to validate assumptions"},{"id":"d","text":"It makes metrics unnecessary"}]'::jsonb,
'{"correctOptionId":"a"}'::jsonb,
'{"correctFeedback":"A specific segment helps the team reason about concrete needs and tradeoffs.","incorrectFeedback":"Segmentation narrows the problem space; it does not eliminate uncertainty."}'::jsonb,
'["product-strategy","segmentation"]'::jsonb,'SEEDED','role-bank-h1',true),
('72000000-0000-0000-0000-000000000043','10000000-0000-0000-0000-000000000031','north-star','MCQ',2,
'What is a useful property of a North Star metric?',
'[{"id":"a","text":"It reflects recurring value delivered to customers and connects to sustainable product success"},{"id":"b","text":"It must always be total page views"},{"id":"c","text":"It should change only once a year"},{"id":"d","text":"It replaces all guardrail metrics"}]'::jsonb,
'{"correctOptionId":"a"}'::jsonb,
'{"correctFeedback":"A useful North Star metric connects customer value with durable product progress.","incorrectFeedback":"The metric should represent delivered value, not merely a convenient activity count."}'::jsonb,
'["product-strategy","north-star-metric"]'::jsonb,'SEEDED','role-bank-h1',true),
('72000000-0000-0000-0000-000000000044','10000000-0000-0000-0000-000000000031','strategy-tradeoff','SCENARIO',3,
'Usage is growing, but retention is falling after the first week. The team proposes adding more acquisition campaigns. What would you investigate before committing to that strategy?',
null,
'{"referenceAnswer":"Investigate where and why users fail to receive recurring value, segment retention/cohorts, validate the activation and retention problem, and avoid scaling acquisition before understanding the retention leak.","expectedKeywords":["retention","cohort","value","acquisition"]}'::jsonb,
'{"criteria":[{"id":"diagnose","weight":0.55,"description":"Prioritizes diagnosing retention and recurring value before scaling acquisition"},{"id":"evidence","weight":0.45,"description":"Uses cohorts/segments or other evidence to localize the problem"}],"maxScore":1}'::jsonb,
'["product-strategy","retention","tradeoffs"]'::jsonb,'SEEDED','role-bank-h1',true)

on conflict(id) do update set
  skill_id=excluded.skill_id,
  concept_id=excluded.concept_id,
  type=excluded.type,
  difficulty=excluded.difficulty,
  prompt=excluded.prompt,
  options=excluded.options,
  answer_key=excluded.answer_key,
  rubric=excluded.rubric,
  tags=excluded.tags,
  source=excluded.source,
  version=excluded.version,
  is_active=true;
